#!/usr/bin/env python3
"""
make_ram_map.py - Build ram_map.asm with forward declarations for translated banks.

Why this exists:
- The generated bank files reference many shared symbols (ram_/con_/sub_/tbl_/etc.).
- Some of those are normal labels (label:), others are constants defined with EQU or =.
- vasm can choke on these cross-bank references unless it sees declarations up front.

This script scans all bank_*_gen68k_vdp.asm files and writes ram_map.asm containing:
- XREF declarations for global labels and subroutines
- EQU definitions copied through for global constants
- = assignments copied through for global constants

Run this after patch_vdp.py / fix_syntax.py and before build.bat.
"""

from __future__ import annotations

import glob
import os
import re
import sys
from collections import defaultdict

# Global things that may legitimately be referenced across bank files.
GLOBAL_PREFIXES = (
    'ram_', 'con_', 'sub_', 'loc_', 'tbl_',
    'fn_', 'init_', 'bat_', 'vec_', 'ofs_'
)

# label:
LABEL_DEF = re.compile(r'^([A-Za-z_][A-Za-z0-9_]*):\s*(?:;.*)?$')
# NAME EQU value
EQU_DEF = re.compile(r'^([A-Za-z_][A-Za-z0-9_]*)\s+EQU\s+(.+?)(?:\s*;.*)?$', re.IGNORECASE)
# NAME = value
ASSIGN_DEF = re.compile(r'^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+?)(?:\s*;.*)?$')


def is_global_symbol(name: str) -> bool:
    n = name.lower()
    return any(n.startswith(p) for p in GLOBAL_PREFIXES)


def collect_symbols(filepath: str):
    labels: list[str] = []
    equs: dict[str, str] = {}
    assigns: dict[str, str] = {}

    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        for raw_line in f:
            line = raw_line.rstrip()
            if not line or line.lstrip().startswith(';'):
                continue

            m = LABEL_DEF.match(line)
            if m:
                name = m.group(1)
                if is_global_symbol(name):
                    labels.append(name)
                continue

            m = EQU_DEF.match(line)
            if m:
                name, value = m.group(1), m.group(2).strip()
                if is_global_symbol(name) and name not in equs:
                    equs[name] = value
                continue

            m = ASSIGN_DEF.match(line)
            if m:
                name, value = m.group(1), m.group(2).strip()
                if is_global_symbol(name) and name not in assigns:
                    assigns[name] = value
                continue

    return labels, equs, assigns


def main() -> int:
    files = sorted(glob.glob('bank_*_gen68k_vdp.asm'))
    if not files:
        files = sorted(glob.glob('bank_*_vdp.asm'))
    if not files:
        print('No bank files found!')
        return 1

    label_first_src: dict[str, str] = {}
    equ_first_src: dict[str, tuple[str, str]] = {}
    assign_first_src: dict[str, tuple[str, str]] = {}

    for path in files:
        labels, equs, assigns = collect_symbols(path)

        for name in labels:
            label_first_src.setdefault(name, path)

        for name, value in equs.items():
            equ_first_src.setdefault(name, (value, path))

        for name, value in assigns.items():
            assign_first_src.setdefault(name, (value, path))

    out_path = 'ram_map.asm'
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('; ram_map.asm - Auto-generated by make_ram_map.py\n')
        f.write('; Forward declarations for cross-bank globals used by vasm.\n')
        f.write('; Re-run make_ram_map.py whenever bank_*_gen68k_vdp.asm changes.\n\n')

        if label_first_src:
            f.write('; ---- Cross-bank global labels/subroutines ----\n')
            by_src: dict[str, list[str]] = defaultdict(list)
            for name, src in sorted(label_first_src.items()):
                by_src[src].append(name)
            for src in sorted(by_src):
                f.write(f'; from {src}\n')
                for name in sorted(by_src[src]):
                    f.write(f'    XREF    {name}\n')
                f.write('\n')

        if equ_first_src:
            f.write('; ---- Global constants defined with EQU ----\n')
            by_src_e: dict[str, list[tuple[str, str]]] = defaultdict(list)
            for name, (value, src) in sorted(equ_first_src.items()):
                by_src_e[src].append((name, value))
            for src in sorted(by_src_e):
                f.write(f'; from {src}\n')
                for name, value in sorted(by_src_e[src]):
                    f.write(f'{name} EQU {value}\n')
                f.write('\n')

        if assign_first_src:
            f.write('; ---- Global constants defined with = ----\n')
            by_src_a: dict[str, list[tuple[str, str]]] = defaultdict(list)
            for name, (value, src) in sorted(assign_first_src.items()):
                by_src_a[src].append((name, value))
            for src in sorted(by_src_a):
                f.write(f'; from {src}\n')
                for name, value in sorted(by_src_a[src]):
                    f.write(f'{name} = {value}\n')
                f.write('\n')

    print('=' * 55)
    print('  RAM MAP REPORT')
    print('=' * 55)
    print(f'  Files scanned: {len(files)}')
    print(f'  Label XREFs:   {len(label_first_src)}')
    print(f'  EQU copied:    {len(equ_first_src)}')
    print(f'  = copied:      {len(assign_first_src)}')
    print(f'  Written:       {out_path}')
    print('\n  main.asm should include:')
    print('      INCLUDE "ram_map.asm"')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
